services:
  # Backend Service
  - type: web
    name: azure-suites-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3001
      - key: FRONTEND_URL
        value: https://azure-suites.onrender.com
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_SECURE
        value: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        value: "Azure Suites Hotel <noreply@azuresuites.com>"

  # Frontend Service
  - type: web
    name: azure-suites
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://azure-suites-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
